language: python
sudo: false

before_install:
  - rvm install 2.2
  - rvm use 2.2
  - gem install hiptest-publisher
  - hiptest-publisher -c python-unittest.conf --only=tests --test-run-id=1357

script:
 - python bootstrap.py
 - bin/buildout
 - bin/test --with-tap

after_script:
  - hiptest-publisher -c python-unittest.conf --push="*.tap" --test-run-id=1357
